var miNumero = 0;
miNumero = 10 + 20;
miNumero = 2.5;
console.log(miNumero);
var booleano = true;
booleano = false;
var encendido;
encendido = true;
console.log("Encendido es:", encendido);
console.log("Encendido es:", { encendido: encendido });
encendido = true && false;
console.log("Encendido es:", encendido);
var normal = 'hola';
normal = true;
normal = 10;
normal = 11.25;
console.log("Normal es:", normal);
